version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    image: python:3.11-slim
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - books_data:/data/books
      - audio_data:/data/audio
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - books_data:/data/books
      - audio_data:/data/audio
    command: sh -c "pip install -r requirements.txt && celery -A app.tasks worker --loglevel=info"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - backend

  frontend:
    image: node:18-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0"
    ports:
      - "3001:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  voice-clone:
    build: ./voice-clone
    ports:
      - "5002:5002"
    volumes:
      - ./voice-clone/app/voice_samples:/app/app/voice_samples
      - ./voice-clone/output:/app/output
    restart: unless-stopped


volumes:
  redis_data:
  books_data:
  audio_data:
